CC = gcc
RM = -rm -f

LIBPATH = -L"/System/Library/Frameworks/OpenGL.framework/Libraries"
LIBS = -framework GLUT -framework OpenGL

DEF = -DUSE_MAC=1
INCLUDE =
CFLAGS = $(INCLUDE) $(DEF) -g -fomit-frame-pointer -Wall
LDFLAGS = $(LIBPATH) $(LIBS)

TARGETS = 3drace
OBJECTS = $(TARGETS).o

all: $(TARGETS)


%.o: %.c
	$(CC) $(CFLAGS) -c $*.c

$(TARGETS): $(OBJECTS)
	$(CC) $< $(LDFLAGS) -o $@


clean:
	$(RM) $(TARGETS) $(OBJECTS)

