CC = gcc
RM = -rm -f

LIBS = -framework GLUT -framework OpenGL

DEF =
INCLUDE =
CFLAGS = $(INCLUDE) $(DEF) -g -fomit-frame-pointer -Wall
LDFLAGS = $(LIBS)

TARGETS = 3drace
OBJECTS = $(TARGETS).o

all: $(TARGETS)


%.o: %.c
	$(CC) $(CFLAGS) -c $*.c

$(TARGETS): $(OBJECTS)
	$(CC) $< $(LDFLAGS) -o $@


clean:
	$(RM) $(TARGETS) $(OBJECTS)

